version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'production'
      PASSENGER_APP_ENV: 'production'
volumes:
  gems: {}
